#H2 Config
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:todolist
    driverClassName: org.h2.Driver
    username: user
    password: password

#Jackson JSON
  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
    deserialization:
      use-long-for-ints: true
      accept-single-value-as-array: true
