#H2 Config
spring:
  jpa:
    database-platform: com.chilborne.todoapi.persistance.dialect.SQLiteDialect
    hibernate:
      dll-auto: update
  datasource:
    url : jdbc:sqlite:TO_DO.sqlite
    direver-class-name: org.sqlite.JDBC
    username: admin
    password: password


  #Jackson JSON
  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
    deserialization:
      use-long-for-ints: true
      accept-single-value-as-array: true
