package com.chilborne.todoapi.persistance.dto;

import com.chilborne.todoapi.persistance.validation.OnPersist;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Null;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;
import java.util.LinkedList;
import java.util.List;
import java.util.Objects;

@ApiModel(value = "To-Do List")
public class ToDoListDto {

    @ApiModelProperty(name = "list_id")
    private long listId;

    @NotBlank(groups = OnPersist.class, message = "name is compulsory")
    private String name;

    @Size(min = 3, max = 255, message = "description must be between 3 and 255 characters long")
    private String description;

    @ApiModelProperty(name = "date_time_made", dataType = "LocalDateTime", notes = "autogenerated on To-Do List creation")
    @JsonFormat(pattern="dd-MM-yyyy HH:mm:ss")
    @Null(groups = OnPersist.class, message = "date_time_made is automatically generated on list creation")
    private LocalDateTime dateTimeMade;

    private List<TaskDto> tasks = new LinkedList<>();

    @ApiModelProperty(notes = "To-Do List is activated on creation")
    @Null(groups = OnPersist.class, message = "To-Do List is activated on creation")
    private boolean active = true;

    @Null(groups = OnPersist.class, message = "url is autogenerated on list creation")
    private String url;

    public ToDoListDto() {
    }

    public long getListId() {
        return listId;
    }

    public void setListId(long listId) {
        this.listId = listId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDateTime getDateTimeMade() {
        return dateTimeMade != null ? dateTimeMade.withNano(0) : null;
    }

    public void setDateTimeMade(LocalDateTime dateTimeMade) {
        this.dateTimeMade = dateTimeMade;
    }

    public List<TaskDto> getTasks() {
        return tasks;
    }

    public void setTasks(List<TaskDto> tasks) {
        this.tasks = tasks;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ToDoListDto that = (ToDoListDto) o;

        if (active != that.active) return false;
        if (!Objects.equals(name, that.name)) return false;
        if (!Objects.equals(description, that.description)) return false;
        if (!Objects.equals(dateTimeMade, that.dateTimeMade)) return false;
        return Objects.equals(tasks, that.tasks);
    }

    @Override
    public int hashCode() {
        int result = 31 + (name != null ? name.hashCode() : 0);
        result = 31 * result + (description != null ? description.hashCode() : 0);
        result = 31 * result + (dateTimeMade != null ? dateTimeMade.hashCode() : 0);
        result = 31 * result + (tasks != null ? tasks.hashCode() : 0);
        result = 31 * result + (active ? 1 : 0);
        return result;
    }
}
